name: odm-cli-extensions-starter CI/CD

on:
  release:
    types: [ created ]

jobs:
  verify-version:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: read
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: maven
      - name: Get Git Tag
        run: |
          TAG_VERSION=$(echo "${{ github.ref_name }}" | sed 's/[^0-9.]//g')
          echo "TAG_VERSION=${TAG_VERSION}" >> $GITHUB_ENV
      - name: Get Maven Version
        run: |
          MAVEN_VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
          echo "MAVEN_VERSION=${MAVEN_VERSION}" >> $GITHUB_ENV
      - name: Check Tag and Version Match
        run: |
          if [ "${{ env.TAG_VERSION }}" != "${{ env.MAVEN_VERSION }}" ]; then
            echo "Git tag (${{ env.TAG_VERSION }}) does not match POM version (${{ env.MAVEN_VERSION }})"
            exit 1
          fi
      - name: Set up Maven settings
        run: |
          mkdir -p ~/.m2
          echo "<settings>
            <servers>
              <server>
                <id>odm-spec-parser-repo</id>
                <username>your-github-username</username>
                <password>${{ secrets.GITHUB_TOKEN }}</password>
              </server>
              <server>
                <id>odm-cli-extensions-repo</id>
                <username>your-github-username</username>
                <password>${{ secrets.GITHUB_TOKEN }}</password>
              </server>
            </servers>
          </settings>" > ~/.m2/settings.xml
      - name: Execute tests with Maven
        run: mvn -B test

  deploy-jar:
    runs-on: ubuntu-latest
    needs: verify-version
    permissions:
      contents: write
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: maven
      - name: Set up Maven settings
        run: |
          mkdir -p ~/.m2
          echo "<settings>
            <servers>
              <server>
                <id>odm-spec-parser-repo</id>
                <username>your-github-username</username>
                <password>${{ secrets.GITHUB_TOKEN }}</password>
              </server>
              <server>
                <id>odm-cli-extensions-repo</id>
                <username>your-github-username</username>
                <password>${{ secrets.GITHUB_TOKEN }}</password>
              </server>
            </servers>
          </settings>" > ~/.m2/settings.xml
      - name: Build the JAR package
        run: mvn clean package -DskipTests
      - name: Get JAR Version
        run: |
          JAR_VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
          echo "JAR_VERSION=${JAR_VERSION}" >> $GITHUB_ENV
      - name: Upload JAR to GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: target/odm-cli-extension-starter-${{ env.JAR_VERSION }}.jar